// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5P7Zhmg6Ihhbu6QYQkSVG7CnR787uY9Q',
    appId: '1:242679145035:web:bd4caee6ffff9a066d23ce',
    messagingSenderId: '242679145035',
    projectId: 'event-ad263',
    authDomain: 'event-ad263.firebaseapp.com',
    storageBucket: 'event-ad263.firebasestorage.app',
    measurementId: 'G-GKTY0PE9TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4SpPvfsror3NpmrKqV3iMbxGLP5tU6Ys',
    appId: '1:242679145035:android:306ceefb07ff66096d23ce',
    messagingSenderId: '242679145035',
    projectId: 'event-ad263',
    storageBucket: 'event-ad263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0fO5L72vqe1s3a8jzy8H_y6KLCrNkzQ',
    appId: '1:242679145035:ios:7b791eb9507eac076d23ce',
    messagingSenderId: '242679145035',
    projectId: 'event-ad263',
    storageBucket: 'event-ad263.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
